/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC_SAR_1.h"
#include "Potentiometer_1_aliases.h"
#include "Potentiometer_1.h"
#include "PWM_1.h"
#include "Clock_1.h"
#include "Servo1_aliases.h"
#include "Servo1.h"
#include "LCD_Char_1.h"
#include "Clock_2.h"
#include "PWM_2.h"
#include "Servo2_aliases.h"
#include "Servo2.h"
#include "ADC_SAR_2.h"
#include "Potentiometer_2_aliases.h"
#include "Potentiometer_2.h"
#include "ADC_DelSig_1.h"
#include "A_aliases.h"
#include "A.h"
#include "B_aliases.h"
#include "B.h"
#include "C_aliases.h"
#include "C.h"
#include "D_aliases.h"
#include "D.h"
#include "Potentiometer_3_aliases.h"
#include "Potentiometer_3.h"
#include "PWM_3.h"
#include "Servo3_aliases.h"
#include "Servo3.h"
#include "CapSense_CSD.h"
#include "CapSense_CSD_CSHL.h"
#include "CapSense_CSD_Pins.h"
#include "CapSense_CSD_TunerHelper.h"
#include "ADC_SAR_1_IRQ.h"
#include "LCD_Char_1_LCDPort_aliases.h"
#include "LCD_Char_1_LCDPort.h"
#include "ADC_SAR_2_IRQ.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "CapSense_CSD_CompCH0.h"
#include "CapSense_CSD_IdacCH0.h"
#include "CapSense_CSD_AMuxCH0.h"
#include "CapSense_CSD_IntClock.h"
#include "cy_em_eeprom.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"

/*[]*/

